name: Supabase Keep Alive

on:
  schedule:
    # Esegue alle 00:00 ogni Lunedi e Giovedi
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # Ti permette di avviarlo a mano per testare

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Supabase
        run: |
          curl -i -X GET "https://gqxstkjgyrhwfdsvtpuv.supabase.co/rest/v1/units?select=*&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
